SELECT DATE_DIM.CALMONTH,
	CUST_VENDOR_DIM.ADDRCATCODE1,
	SUM(INVENTORY_FACT.EXTCOST) AS SUMEXTCOST,
	SUM(INVENTORY_FACT.QUANTITY) AS SUMQUNTITY
FROM INVENTORY_FACT
JOIN TRANS_TYPE_DIM ON TRANS_TYPE_DIM.TRANSTYPEKEY = INVENTORY_FACT.TRANSTYPEKEY
JOIN DATE_DIM ON DATE_DIM.DATEKEY = INVENTORY_FACT.DATEKEY
JOIN CUST_VENDOR_DIM ON CUST_VENDOR_DIM.CUSTVENDORKEY = INVENTORY_FACT.CUSTVENDORKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 5
	AND DATE_DIM.CALYEAR = 2011
GROUP BY DATE_DIM.CALMONTH, CUST_VENDOR_DIM.ADDRCATCODE1
UNION
SELECT DATE_DIM.CALMONTH,
	NULL,
	SUM(INVENTORY_FACT.EXTCOST) AS SUMEXTCOST,
	SUM(INVENTORY_FACT.QUANTITY) AS SUMQUNTITY
FROM INVENTORY_FACT
JOIN TRANS_TYPE_DIM ON TRANS_TYPE_DIM.TRANSTYPEKEY = INVENTORY_FACT.TRANSTYPEKEY
JOIN DATE_DIM ON DATE_DIM.DATEKEY = INVENTORY_FACT.DATEKEY
JOIN CUST_VENDOR_DIM ON CUST_VENDOR_DIM.CUSTVENDORKEY = INVENTORY_FACT.CUSTVENDORKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 5
	AND DATE_DIM.CALYEAR = 2011
GROUP BY DATE_DIM.CALMONTH
UNION
SELECT NULL,
	CUST_VENDOR_DIM.ADDRCATCODE1,
	SUM(INVENTORY_FACT.EXTCOST) AS SUMEXTCOST,
	SUM(INVENTORY_FACT.QUANTITY) AS SUMQUNTITY
FROM INVENTORY_FACT
JOIN TRANS_TYPE_DIM ON TRANS_TYPE_DIM.TRANSTYPEKEY = INVENTORY_FACT.TRANSTYPEKEY
JOIN DATE_DIM ON DATE_DIM.DATEKEY = INVENTORY_FACT.DATEKEY
JOIN CUST_VENDOR_DIM ON CUST_VENDOR_DIM.CUSTVENDORKEY = INVENTORY_FACT.CUSTVENDORKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 5
	AND DATE_DIM.CALYEAR = 2011
GROUP BY CUST_VENDOR_DIM.ADDRCATCODE1
UNION
SELECT NULL,
	NULL,
	SUM(INVENTORY_FACT.EXTCOST) AS SUMEXTCOST,
	SUM(INVENTORY_FACT.QUANTITY) AS SUMQUNTITY
FROM INVENTORY_FACT
JOIN TRANS_TYPE_DIM ON TRANS_TYPE_DIM.TRANSTYPEKEY = INVENTORY_FACT.TRANSTYPEKEY
JOIN DATE_DIM ON DATE_DIM.DATEKEY = INVENTORY_FACT.DATEKEY
JOIN CUST_VENDOR_DIM ON CUST_VENDOR_DIM.CUSTVENDORKEY = INVENTORY_FACT.CUSTVENDORKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 5
	AND DATE_DIM.CALYEAR = 2011
ORDER BY 1, 2
