SELECT COMPANY_DIM.COMPANYNAME,
	BRANCH_PLANT_DIM.BPNAME,
	SUM(INVENTORY_FACT.EXTCOST) AS SUMEXTCOST,
	SUM(INVENTORY_FACT.QUANTITY) AS SUMQUANTITY
FROM INVENTORY_FACT
JOIN TRANS_TYPE_DIM ON TRANS_TYPE_DIM.TRANSTYPEKEY = INVENTORY_FACT.TRANSTYPEKEY
JOIN BRANCH_PLANT_DIM ON BRANCH_PLANT_DIM.BRANCHPLANTKEY = INVENTORY_FACT.BRANCHPLANTKEY
JOIN COMPANY_DIM ON COMPANY_DIM.COMPANYKEY = BRANCH_PLANT_DIM.COMPANYKEY
WHERE INVENTORY_FACT.TRANSTYPEKEY = 2
GROUP BY ROLLUP(COMPANY_DIM.COMPANYNAME, BRANCH_PLANT_DIM.BPNAME)
ORDER BY GROUPING(COMPANY_DIM.COMPANYNAME, BRANCH_PLANT_DIM.BPNAME), COMPANY_DIM.COMPANYNAME,
				BRANCH_PLANT_DIM.BPNAME
